package ui;


import java.net.URL;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.layout.Pane;


public class GameOptionsScene implements javafx.fxml.Initializable{
	@FXML private Pane gameOptionsPane;
	@FXML private Button newGameButton;
	@FXML private Button chainGameTitle;
	@FXML private Button helpButton;

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		mainChainGameCustomFont();
		setNewGameEventHandler();
		setHelpButtonEventHandler();
	}

	private void setHelpButtonEventHandler() {
		helpButton.setOnAction((event) -> {
			String message = "<html><span style='font-size:25'>Chain Game generated by Group A, 2014. <br> Project for CMPT 373 <br><br> </span>"
					+ "<span style='font-size:20'> Rules: <br> 1. Players will take turns placing pegs onto the board <br> </span>"
					+ "<span style='font-size:20'> 2. Pegs that are knight's position away from each other will form a connection <br> </span>"
					+ "<span style='font-size:20'> 3. Connections that are intercepted by an opponent's connection will not form <br> </span>"
					+ "<span style='font-size:20'> 4. Players are not allowed to place a peg onto the opponents edges <br> </span>"
					+ "<span style='font-size:20'> 5. First player to be able to form a connection from edge to edge wins the game <br><br> </span>"
					+ "<span style='font-size:20'> How to Play: <br> </span>"
					+ "<span style='font-size:20'> 1. Select a hole that does not contain a peg to place your peg <br> </span>"
					+ "<span style='font-size:20'> 2. Player's turn will end when a peg is placed and other player's turn will begin</span></html>";
			SwingUtilities.invokeLater(()->JOptionPane.showMessageDialog(null, message, "Help",JOptionPane.INFORMATION_MESSAGE));
		});
	}

	private void setNewGameEventHandler() {
		newGameButton.setOnAction( (event) -> SceneLoader.loadScene(gameOptionsPane, "ChooseModeScene.fxml"));
	}
	
	private void mainChainGameCustomFont(){
		CustomFonts.setCustomButtonFont(newGameButton,"NEW GAME");
		CustomFonts.setCustomTitleButtonFont(chainGameTitle,"CHAIN GAME");
		CustomFonts.setCustomButtonFont(helpButton, "HELP");
	}
}